# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    az login --use-device-code
    az group create -n ARMPipelinep -l eastus
    az deployment group validate --resource-group ARMPipelinep --template-file ARMTemplate.json
  displayName: 'Validating Tempate File'

- script: |
    az deployment group create --resource-group ARMPipelinep --template-file ARMTemplate.json
  displayName: 'Deploying resources to azure'
